# Generated by Django 4.0.4 on 2023-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_fistname_customer_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
