# Generated by Django 4.0.4 on 2023-03-01 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=200)),
                ('price', models.FloatField(max_length=200)),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.CharField(default='Place-Date', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='workshops',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.workshops'),
        ),
    ]
