# Generated by Django 4.0.4 on 2023-03-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_workshops_workshop_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workshop',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='workshop',
            new_name='product',
        ),
    ]
