# Generated by Django 4.0.4 on 2023-03-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_workshop_product_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Customer Bookings', 'verbose_name_plural': 'Customer Bookings'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Workshops', 'verbose_name_plural': 'Workshops'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Customer Booking Information', 'verbose_name_plural': 'Customer Booking Information'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
