# Generated by Django 4.0.4 on 2023-06-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_dateandplace_product_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date',
            field=models.CharField(default='Place-Date', max_length=400),
        ),
    ]
